### ISSUE TITLE
Crashes/Doesn't Open

### ISSUE THREAD

**Issue by JewbaccaYT** [magneticflux-/fabric-mumblelink-mod#10]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors!

I get this message when trying to open Minecraft

**Comment by magneticflux-** [comment]
Please post the entire log to Pastebin or something and link that here.

**Comment by JewbaccaYT** [comment]
https://pastebin.com/6EbnDBbC Thanks in advance

**Comment by JewbaccaYT** [comment]
Both me and my friend have this issue.

**Comment by magneticflux-** [comment]
Have you installed the Fabric API? https://www.curseforge.com/minecraft/mc-mods/fabric-api

**Comment by JewbaccaYT** [comment]
Hey sorry man, this was a dumb by me, we both hadn't installed API, and I had an outdated version of Fabric.

**Comment by magneticflux-** [comment]
No problem, glad I could help!
