### ISSUE TITLE
"Invalid payload" error while connecting to Spigot server

### ISSUE THREAD

**Issue by BobTagnil** [magneticflux-/fabric-mumblelink-mod#22]
Hi first I'm glad to see an active repo for MumbleLink on MC even more using Fabric 👍 

"Bukkit" is complaining about message size over 32 characters, any idea where does it come from ? 
I don't understand how this mod could throw an error on the server side given that it doesn't need that many informations outside of position, right ?

Also of course it works properly on solo but I didn't tried it on LAN...

Logs are attached

[client.log](https://github.com/magneticflux-/fabric-mumblelink-mod/files/4497939/client.log)
[server.log](https://github.com/magneticflux-/fabric-mumblelink-mod/files/4497940/server.log)

**Comment by magneticflux-** [comment]
This was interesting to debug! This is the Git Blame for the cause of the issue: [Spigot Messenger.java](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/plugin/messaging/Messenger.java#27).

Here's my vague history of custom packets:
- Jan. 2012: Dinnerbone creates the API [blog post](https://dinnerbone.com/blog/2012/01/13/minecraft-plugin-channels-messaging/)
    - This is around the 1.1/1.2 update?
    - The max length is 16 chars.
- Sometime before Aug. 2017: The length is increased
    - Sometime before the 1.11 update
    - New length is 20 chars.
- During the 1.11 update: The length is increased
    - New length is 32 chars?
- During the 1.13 update: The length cap is removed
    - According to this protocol wiki change ([link](https://wiki.vg/index.php?title=Plugin_channels&oldid=14556)) by Pokechu22, a Mojira mod
    - Technically limited to 32767 chars by `PacketByteBuffer#writeString(String)`

Given this information, and the commit by md_5 updating Spigot to 1.13-pre7 [here](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/f8b2086d60942eb2cd7ac25a2a1408cb790c222c#src/main/java/org/bukkit/plugin/messaging/Messenger.java) only changing the limit from 20 to 32, it seems like a bug in Spigot. During the 1.13 update of Spigot, they should have removed the hard limit.

I'll open an issue on their JIRA link these two.

**Comment by magneticflux-** [comment]
@BobTagnil I opened an issue on Spigot's JIRA [here](https://hub.spigotmc.org/jira/browse/SPIGOT-5681). Please vote there to encourage it to be resolved faster.

**Comment by BobTagnil** [comment]
Great ! 
As a temporary fix I compiled the mod on my computer in order to fix it.

Thank you again for the support of this mumble feature

**Comment by Kuratius** [comment]
Can you make it configurable whether the client sends a custom packet? There are still a lot of spigot servers that reject it.
