### ISSUE TITLE
Is it possible to turn the server component of the mod into a paper/spigot plugin?

### ISSUE THREAD

**Issue by Kuratius** [magneticflux-/fabric-mumblelink-mod#26]

**Comment by magneticflux-** [comment]
Theoretically, yes. The mod communicates over Plugin Channels, so if you can create a channel with the correct name and send packets that match the mod, it will work.

I don't have any experience with plugin development and I won't be working on it or adding it to this repo, so I'll close this as `wontfix` for now.
