### ISSUE TITLE
Positional audio not working with Mumble

### ISSUE THREAD

**Issue by ArvickC** [magneticflux-/fabric-mumblelink-mod#30]
Hey, so I'm using this plugin and it isn't working, i don't know what im doing wrong, i connected to my mumble server and the proximity isn't working, i tested this multiple times it just didn't work, but as soon as i switched to Badlion Client, the badlion mod worked... i have no idea whats wrong?

**Comment by magneticflux-** [comment]
Please attach logs of loading the mods.

**Comment by ArvickC** [comment]
How do i do that? (sorry im not that smart lol)

**Comment by magneticflux-** [comment]
It depends on the launcher you use. They'll be in `.minecraft/logs`, shown [here](https://minecraft.gamepedia.com/.minecraft#.minecraft_file_hierarchy). `latest.log` is the last time you launched the game and includes all the diagnostic information I need.

**Comment by ArvickC** [comment]
If i use twitch/curseforge then?

**Comment by magneticflux-** [comment]
I don't have any experience with the Twitch App, does this work? https://help.twitch.tv/s/article/information-retrieval-for-troubleshooting?language=en_US#RetrievingGameOutputlog

**Comment by ArvickC** [comment]
Ok! lemmie check it out!

**Comment by ArvickC** [comment]
Ah Ok! Lemmie launch minecraft, ill paste it in a hastebin!

**Comment by ArvickC** [comment]
Here is the logs = https://hasteb.in/owomogid.pl

**Comment by magneticflux-** [comment]
Those logs are just the startup and don't show any errors. I need logs while Mumble Link is active (in a world or server).

Also, I assume you followed the Mumble guide on how to enable positional audio in the first place? https://wiki.mumble.info/wiki/Positional-Audio#How_to_activate_Positional_Audio

**Comment by ArvickC** [comment]
Yeah, should i join a world then get the logs?

**Comment by magneticflux-** [comment]
Yes, that will print some diagnostic information about linking to Mumble and any failures encountered to the log. The Mumble client should also say "Minecraft Mumble Link Mod linked." in the Mumble chat if Mumble is open when you join a world/server.

**Comment by ArvickC** [comment]
Ok! Let me go do that!

**Comment by ArvickC** [comment]
I joined my server and in mumble it said, "Minecraft Mumble Link Mod linked." this is the hastebin : https://hastebin.com/akunoxutiq.md

**Comment by magneticflux-** [comment]
Showing the message in Mumble is good; it means the mod links properly.

Those logs seem incomplete, and they don't mention Mumble Link anywhere. Are you sure that's the whole log file and it's the right one?

**Comment by ArvickC** [comment]
Oh, let me rejoin and do it again...

**Comment by ArvickC** [comment]
Is this it: https://hastebin.com/orahevibab.md ?

If this doesn't work ill launch normal minecraft and drag the latest.log

**Comment by magneticflux-** [comment]
That's still only a small portion of the logs. You should try to navigate to the `.minecraft` folder and get the log files directly from there. You can get there by clicking "Open resource pack folder" and then going up one folder.

**Comment by ArvickC** [comment]
Hmm ok, im using curseforge tho, lemmie launch in normal minecraft with the mod... Then is it the latest.log file?

**Comment by magneticflux-** [comment]
It should be the same with Curseforge or the Vanilla Launcher (or any other launcher probably).

**Comment by ArvickC** [comment]
Oh ok!

**Comment by ArvickC** [comment]
[latest.log](https://github.com/magneticflux-/fabric-mumblelink-mod/files/5112121/latest.log)
Here is the log

**Comment by magneticflux-** [comment]
That log seems to cut off as well. Start Minecraft, join a world or server, close Minecraft, and then do the same steps that you just did to get `latest.log`.

**Comment by ArvickC** [comment]
Oh Ok!

**Comment by ArvickC** [comment]
[latest.log](https://github.com/magneticflux-/fabric-mumblelink-mod/files/5112132/latest.log)
Is this good?

**Comment by ArvickC** [comment]
Um, Hello?

**Comment by Kuratius** [comment]
> [latest.log](https://github.com/magneticflux-/fabric-mumblelink-mod/files/5112132/latest.log)
> Is this good?

May sound naive, but have you tried removing your duplicate fabric api versions and all your other mods?

**Comment by magneticflux-** [comment]
> 
> 
> I joined my server and in mumble it said, "Minecraft Mumble Link Mod linked." this is the hastebin : https://hastebin.com/akunoxutiq.md

This indicates everything is working fine on the mod's end. Please make sure you have Mumble configured properly: https://wiki.mumble.info/wiki/Positional-Audio
