### ISSUE TITLE
MumbleLink not linking with Mumble on Linux.

### ISSUE THREAD

**Issue by w3bb** [magneticflux-/fabric-mumblelink-mod#36]
https://paste.ee/p/blzwX

The log reports that it is linked to my Mumble client. Nothing happens on the Mumble client. My friend on Windows says he can see a message saying it's been linked on Mumble, but I don't see anything.

**Comment by magneticflux-** [comment]
You have to enable "Link to game and transmit position" in Mumble.

**Comment by w3bb** [comment]
> You have to enable "Link to game and transmit position" in Mumble.

I already did, as well as the option in audio output

**Comment by magneticflux-** [comment]
Can you clone this repo https://github.com/magneticflux-/java-mumble-link and run `./gradlew test` and show the full log? You'll need a version of the JDK on your path variable.

**Comment by w3bb** [comment]
@magneticflux- https://hastebin.com/raw/exomoroqux

**Comment by magneticflux-** [comment]
You cloned this repo, which doesn't have any tests (it's just a wrapper for Minecraft). Clone the one I linked above which does tests for shared memory.

**Comment by w3bb** [comment]
@magneticflux- Oh sorry, I completely missed the java part of the URL, hold on

**Comment by magneticflux-** [comment]
Also, can you show the output of `uname -a`?

**Comment by w3bb** [comment]
https://hastebin.com/raw/duyusudeso

`Linux jumping 5.8.18_1 #1 SMP Sun Nov 1 14:25:13 UTC 2020 x86_64 GNU/Linux`

And just for sanity's sake, here's the options set in Mumble:
![image](https://user-images.githubusercontent.com/34105598/102003914-a3496c80-3cd9-11eb-93bc-9701ab905646.png)
![image](https://user-images.githubusercontent.com/34105598/102003929-c247fe80-3cd9-11eb-877b-1a760e088d0a.png)

**Comment by magneticflux-** [comment]
Can you run `ipcs -a` and `cat /proc/sysvipc/shm` while you're connected to a server in Mumble and in Minecraft and show the output?

**Comment by w3bb** [comment]
https://hastebin.com/raw/vucukobapi
https://hastebin.com/raw/ucugewibax
@magneticflux-

**Comment by magneticflux-** [comment]
In the same way, can you run `ls /dev/shm` `lsof /dev/shm` while everything is connected? (`lsof` might need a package installed)

**Comment by w3bb** [comment]
`[webb@jumping ~]$ ls /dev/shm`
`MumbleLink.1000  jack_db`

https://hastebin.com/raw/opaheledul

**Comment by magneticflux-** [comment]
I've double-checked the code and my implementation exactly mimics the implementation in Mumble's code.

My code: https://github.com/magneticflux-/jvm-shared-memory/blob/6b17a5bf925e56093720c413e448bb91ee08102d/src/main/java/com/skaggsm/sharedmemory/posix/SharedMemoryPOSIX.java#L32

Mumble code: https://github.com/mumble-voip/mumble/blob/3d7f8cc4e5f502652f6660822eb791cec79a61f7/plugins/link/link-posix.cpp#L141

The logs you gave indicate that my code is correctly opening up the shared memory object called "MumbleLink.1000" (1000 being your UID). Mumble hasn't opened anything. Is Mumble running as the same user? What version of Mumble are you using?

The relevant part of the log:
```
COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF    NODE NAME
java      19830 webb  mem    REG   0,23    10580 2729322 /dev/shm/MumbleLink.1000
```

Also, is the "Link v1.2.0" plugin enabled in the plugins list?

**Comment by w3bb** [comment]
![image](https://user-images.githubusercontent.com/34105598/102004474-215c4200-3cdf-11eb-87fd-d8b0b36d966f.png)
So that probably explains that.

**Comment by magneticflux-** [comment]
Ah, something is very wrong with that! This is what it looks like on Windows:
![image](https://user-images.githubusercontent.com/9124288/102004496-e9e99780-3cd6-11eb-9370-1528a2b1a0c1.png)

**Comment by w3bb** [comment]
To be fair a lot of those are Windows-specific, but I'll probably need to bring it up with the Void maintainers. Thank you for the help.

**Comment by magneticflux-** [comment]
No problem, glad we figured this out!

**Comment by w3bb** [comment]
@magneticflux- I'm testing, and it doesn't seem to be working. Neither of us can hear a difference. Should I refetch my shared memory stuff again?

**Comment by w3bb** [comment]
I got the link plugin enabled, and it reports in chat that it's enabled. I just double checked his settings were correct.

**Comment by w3bb** [comment]
(It's entirely possible that it's a Mumble issue)

**Comment by magneticflux-** [comment]
You also might have to adjust the positional audio settings in Mumble. Try checking the "headphones" box maybe?

**Comment by w3bb** [comment]
> You also might have to adjust the positional audio settings in Mumble. Try checking the "headphones" box maybe?

Did this, still no effect. Is there some sort of indicator for positional audio because I don't see any.

**Comment by magneticflux-** [comment]
If it says `Linked to "Minecraft MumbleLink Mod"` in the Mumble chat it's working and receiving data, so there must be some misconfiguration of audio device output. Are you using mono-channel sound?

**Comment by w3bb** [comment]
Hmm, then yeah it's probably Mumble. I'll probably end up opening a bug report there. Thanks for the help as always.
