### ISSUE TITLE
Dimension Switching doesn't Work

### ISSUE THREAD

**Issue by StarsDown64** [magneticflux-/fabric-mumblelink-mod#42]
I can't seem to get the dimension switching feature to work, nor can any of my friends.

I have my server set up as follows in screenshot 1, and my fabric mod settings are in screenshot 2
![image](https://user-images.githubusercontent.com/19573997/103237559-f21c1680-4915-11eb-857f-43d1195f16d2.png)
![image](https://user-images.githubusercontent.com/19573997/103237675-56d77100-4916-11eb-89f7-8464b7371cfd.png)

Please let me know if any of the setup is wrong.
If it is not, I will add one other thing: I switched to a forge version of this idea and it worked fine, but every time I switched dimensions I would get a message that says `Opening URL mumble://127.0.0.1:64738/Minecraft/Overworld` and likewise for each dimension. This does not appear when switching dimensions with this mod. Therefore, I think a possible lead is that the mod never sends the URI to Mumble, but I'm not sure, I can't read kotlin very well.

Thank you for the help.

**Comment by magneticflux-** [comment]
- Are you running this on a dedicated (standalone) server or an integrated (Open to LAN) server?
- Are there any messages in the Mumble chat?
- Is that the actual IP you're using or are you using a different host?

**Comment by StarsDown64** [comment]
Dedicated server that I don't own. It runs paper so it doesn't use your plugin.
No, there are 0 messages in the mumble chat, other than some mute/unmute unrelated things, and the `Minecraft Mumble Link Mod linked.` message when I load up.
That is the actual IP, I'm using murmur to localhost the Mumble server. My friend is connected successfully using my IP (in a dns of course) and some port forwarding on my end.

**Comment by magneticflux-** [comment]
I clarified my questions above.

**Comment by StarsDown64** [comment]
As did I

**Comment by StarsDown64** [comment]
And I now understand why you are concerned about the first thing. Are you saying the server requires this plugin for this function?

**Comment by magneticflux-** [comment]
Yep, the server must send the dimension data to move players automatically. Having the client change dimension could be possible, I'll create a new issue to track that enhancement #43. In the meantime, you can use the [trivial configuration](https://github.com/magneticflux-/fabric-mumblelink-mod#trivial) to configure pseudo-channel switching by translating players vertically based on dimension.

**Comment by StarsDown64** [comment]
We moved to that idea after realizing it wasn't working so I will. I've seen fabric client mods that can track dimensions, so I wish you luck in implementing a client-controlled version. Personally, I think it would help out greatly, as it wouldn't require the server to run fabric. To my knowledge, most servers run a form of Bukkit.

**Comment by magneticflux-** [comment]
I'll close this then since the original question seems resolved, and you can subscribe to the new issue to track implementation progress of the new feature.

**Comment by magneticflux-** [comment]
Also, thank you for mentioning the Forge version. I looked into it and it illegally uses my code (licensed under the LGPL) without credit or source availability, so I've filed a copyright notice.

**Comment by StarsDown64** [comment]
Hmm, weird. I didn't specify which forge version I used. To my knowledge, https://www.curseforge.com/minecraft/mc-mods/mumblelink is abandoned, and https://www.curseforge.com/minecraft/mc-mods/mumble-integration (the one I was using) doesn't have source code available (obviously you can decompile it but).
