### ISSUE TITLE
I can hear everyone

### ISSUE THREAD

**Issue by Taha-Chaudhry** [magneticflux-/fabric-mumblelink-mod#48]
I can hear everyone in mumble, but everyone else can only hear me when im next to them The mumblink mod is linking, so i know it's not that issue. Can't figure out why it's doing this.

**Comment by magneticflux-** [comment]
You have to enable "Positional Audio"
![image](https://user-images.githubusercontent.com/9124288/103751415-e42d5c00-4fcd-11eb-8c3e-8b78cc904fa4.png)

**Comment by Taha-Chaudhry** [comment]
enable positional audio on mumble?

**Comment by magneticflux-** [comment]
Yes, under the Audio Output tab of the settings.

**Comment by Taha-Chaudhry** [comment]
i've already done that

**Comment by magneticflux-** [comment]
And configure the positional audio settings something like this:
![image](https://user-images.githubusercontent.com/9124288/103751803-746ba100-4fce-11eb-86b0-bd4186df802d.png)
Mainly, set "Minimum Volume" to 0%.

**Comment by Taha-Chaudhry** [comment]
that seemed to work, thanks for responding so quickly.

**Comment by magneticflux-** [comment]
No, problem. I should get around to making a full setup guide for Mumble eventually, since you aren't the first to have issues.
