### ISSUE TITLE
I can hear everyone

### ISSUE THREAD

**Issue by TayderTot** [magneticflux-/fabric-mumblelink-mod#50]
Link to game and transmit position is ticked.

I have the mods in the mod folder

Have all the positional Audio set up below and ticked inthe interface.

Now sure whats up
![f941dd38cb6464373968469106799c7a](https://user-images.githubusercontent.com/77697460/105087982-2637b280-5a50-11eb-8154-eed431e805ef.png)

**Comment by magneticflux-** [comment]
Is the Link plugin enabled in Mumble and is there a message in the Mumble chat when you join a world?

**Comment by TayderTot** [comment]
> Is the Link plugin enabled in Mumble and is there a message in the Mumble chat when you join a world?

It is! It also shows in mumble "Minecraft Mumble Link Mod linked."

**Comment by magneticflux-** [comment]
Everything should be working then. Ensure that all other players have the mod working and configured similar to you.
If a player doesn't have positional audio linked, everyone will hear them.

**Comment by TayderTot** [comment]
> Everything should be working then. Ensure that all other players have the mod working and configured similar to you.
> If a player doesn't have positional audio linked, everyone will hear them.

Everyone hears me as if it works but I can hear everyone clearly. It works for everyone else just I can hear everyone wherever I go. :/

**Comment by magneticflux-** [comment]
Can you share a screenshot of your "Plugins" page in Mumble?
Do other people hear other people correctly?

**Comment by TayderTot** [comment]
> Can you share a screenshot of your "Plugins" page in Mumble?
> Do other people hear other people correctly?

![7e4992bddf685c4afa19ccc0d9337c39](https://user-images.githubusercontent.com/77697460/105093364-749c7f80-5a57-11eb-9319-b5466965e2ef.png)
![34168c5fe80c411ad07765b644739bee](https://user-images.githubusercontent.com/77697460/105093366-749c7f80-5a57-11eb-8ee1-a7ea529181c7.png)

yeah everyone hears others correctly including me. 

I just hear everyone as if I'm in a regular mumble server

**Comment by TayderTot** [comment]
![badf29f209958b7e1a70e3a76797174c](https://user-images.githubusercontent.com/77697460/105093433-97c72f00-5a57-11eb-9483-19419858f940.png)

**Comment by magneticflux-** [comment]
I'm not sure what's wrong then... Make sure all the settings are applied and try restarting Mumble?

**Comment by TayderTot** [comment]
> I'm not sure what's wrong then... Make sure all the settings are applied and try restarting Mumble?

Yeah I restarted mumble, uninstall reinstall, restarted my PC and everything. Everyone can hear me directional etc but everything is totally fucked on my end.

**Comment by TayderTot** [comment]
I GOT THE FIX. So... I use wireless headphones with a GOXLR, I had the wireless headset connected to my PC, but instead connected it to the GOXLR through the AUX cable, it def helped and put all the sound settings through that and when I switched it all it fixed it.

Do I understand why? No. But if anyone else has this issue with this type of settings there you go.

**Comment by magneticflux-** [comment]
Wow, okay then! It might have been an issue with Mumble selecting the audio output device? I'm glad you figured out the issue!

**Comment by TayderTot** [comment]
> Wow, okay then! It might have been an issue with Mumble selecting the audio output device? I'm glad you figured out the issue!

Yeah, I know GOXLR's can give issues including the wireless headset. So I guess keep it noted if anybody else has that issue! I'm very new to my GOXLR and never bothered wiring everything through it until now.
