### ISSUE TITLE
Mumble positional audio settings

### ISSUE THREAD

**Issue by jan-Sanku** [magneticflux-/fabric-mumblelink-mod#53]
Does the mod override mumble's settings for positional audio, or do you have to configure the max audio distance per-client? If the latter is the case, people could easily "cheat" by hearing everyone.
If you *do* have to configure it manually, what are the recommended settings?

(screenshot of the default settings)
![image](https://user-images.githubusercontent.com/56739341/106511554-ad653b80-64d0-11eb-947a-a237053d34a4.png)

**Comment by magneticflux-** [comment]
It is not possible for this mod to override the Mumble settings for positional audio. It is up to the users to configure the Mumble settings.

I personally set minimum volume to 0% and maximum distance to 100m.

**Comment by jan-Sanku** [comment]
Alright, thanks for the quick answer!

**Comment by jan-Sanku** [comment]
@magneticflux- 
Mumble will likely support changing posistional audio in the near future, as stated in [this](https://github.com/mumble-voip/mumble/issues/4575), [this](https://github.com/mumble-voip/mumble/pull/3743), and [this](https://github.com/mumble-voip/mumble/issues/3742) post.
I would suggest re-opening this issue, in case you are going to implement this feature once the plugin framework has been updated.
