### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by srnyx** [magneticflux-/fabric-mumblelink-mod#57]
It's just not working for me I have no clue why...

**Comment by magneticflux-** [comment]
Go through these steps first: https://github.com/magneticflux-/fabric-mumblelink-mod/wiki/Troubleshooting

**Comment by srnyx** [comment]
> Go through these steps first: https://github.com/magneticflux-/fabric-mumblelink-mod/wiki/Troubleshooting

I did. And changing the minimum volume just made it so you couldn't hear anyone.

**Comment by magneticflux-** [comment]
So you see this message? 
![image](https://user-images.githubusercontent.com/9124288/107865332-d966b200-6e2a-11eb-8103-f75ef83e63e3.png)

And the other people do as well?

**Comment by srnyx** [comment]
> So you see this message?
> ![image](https://user-images.githubusercontent.com/9124288/107865332-d966b200-6e2a-11eb-8103-f75ef83e63e3.png)
> 
> And the other people do as well?

Yes

**Comment by magneticflux-** [comment]
That means Mumble is receiving position data, so it's an issue with your Mumble configuration.

Are you all in the same Mumble channel? Are you all in the same Minecraft dimension? Are you close to each other (within a chunk or two)?

**Comment by srnyx** [comment]
> That means Mumble is receiving position data, so it's an issue with your Mumble configuration.
> 
> Are you all in the same Mumble channel? Are you all in the same Minecraft dimension? Are you close to each other (within a chunk or two)?

Yes, yes, yes

**Comment by magneticflux-** [comment]
So all of those are true and you can't hear the other people and the other people can't hear you?

**Comment by srnyx** [comment]
> So all of those are true and you can't hear the other people and the other people can't hear you?

Person 1 can hear person 2. Person 2 can't hear person 1. Person 3 (me) doesn't speak but can hear person 1 and person 2.
And, when someone walks away from someone else, the volume doesn't change (nothing changes).

**Comment by srnyx** [comment]
Well actually.
Person 1 can hear person 2. Person 2 can't hear person 1. Person 3 (me) doesn't speak lmfao

**Comment by magneticflux-** [comment]
In that case ensure all of the above are still true and set the minimum volume to 0% and the maximum distance to 100m. Those parameters control how Mumble treats incoming positional audio (not how it sends positional audio to other people).

Setting the parameters as shown in the Troubleshooting page gives the "expected" experience of not being able to hear distant people at all. Again, those parameters _only_ affect the incoming audio of the person setting them. It doesn't change how the person sounds to other people.

**Comment by srnyx** [comment]
> In that case ensure all of the above are still true and set the minimum volume to 0% and the maximum distance to 100m. Those parameters control how Mumble treats incoming positional audio (not how it sends positional audio to other people).
> 
> Setting the parameters as shown in the Troubleshooting page gives the "expected" experience of not being able to hear distant people at all. Again, those parameters _only_ affect the incoming audio of the person setting them. It doesn't change how the person sounds to other people.

Did that. Don't hear anyone even if I'm directly next to them.

**Comment by magneticflux-** [comment]
Does everyone have their microphones and speakers (or whatever audio i/o) set up in Mumble correctly? Can everyone hear everyone when positional audio is disabled?

Please attach a screenshot of your Mumble settings.

**Comment by srnyx** [comment]
I got it to work! Had to disable the Y-Axis multiplier.
Thank you!

**Comment by srnyx** [comment]
> > So all of those are true and you can't hear the other people and the other people can't hear you?
> 
> Person 1 can hear person 2. Person 2 can't hear person 1. Person 3 (me) doesn't speak but can hear person 1 and person 2.

Still having this issue

**Comment by magneticflux-** [comment]
Ensure that everyone has the y-axis multiplier set to the exact same value and ensure that everyone has their Mumble settings the same as well.

**Comment by srnyx** [comment]
> Ensure that everyone has the y-axis multiplier set to the exact same value and ensure that everyone has their Mumble settings the same as well.

Yeah I made them all redo their settings like 10 times lol
