### ISSUE TITLE
Default config file missing lines.

### ISSUE THREAD

**Issue by iMahco** [magneticflux-/fabric-mumblelink-mod#60]
Ahhh I just spent 3 hours trying to figure out if I was using the wrong mod or something because the configuration file had nothing, so I was stuck staring at the template values with 0 idea on what to do and how to implement them. After installing ModMenu, filling in values, and then hitting save the updated config file adds the missing lines. Just throwing this piece of info out there in hopes that default config file adds the missing lines.
As it stands default config file only has:

>mumbleAutoLaunchOption = "ACCEPT"
>mumbleDimensionYAxisAdjust = 0.0
>voipClient = "MUMBLE"

All is working fine now on my end after the fix mentioned above so no concern there!

**Comment by magneticflux-** [comment]
Take it up with [AutoConfig](https://github.com/shedaniel/AutoConfig), that's what it does by default.

#44 ought to fix this, it moves to a better config API.
