### ISSUE TITLE
1.17 support?

### ISSUE THREAD

**Issue by ojoeth** [magneticflux-/fabric-mumblelink-mod#69]
When will this mod update to 1.17?

**Comment by MenacingPerson** [comment]
+1

**Comment by moxvallix** [comment]
I had a go at compiling and updating it myself; it seems like two of the repositories it used were hosted on a site that has recently been closed down, which makes the build fail (I get a 403 error). Hopefully they are or will be reuploaded elsewhere. If I do manage to get it to compile, I'll submit a PR and link to a compiled jar for anyone whilst we wait for the mod to officially update.

**Comment by magneticflux-** [comment]
https://github.com/zsawyer/MumbleLink/issues/38#issuecomment-861291020

I plan to release an update on the 21st or 22nd. I've been solving update issues in my other mods first since they're less complicated than this one.

**Comment by magneticflux-** [comment]
Here goes nothing! Let me know if anything breaks and I'll put out a patch quickly.
