### ISSUE TITLE
not getting "minecraft mumble mod linked" in chat

### ISSUE THREAD

**Issue by JackBMX637** [magneticflux-/fabric-mumblelink-mod#71]
i am running mumble through serverminer and have tried every possible way I can think of to connect it correctly but I cannot get the linked message or any other signal that it is working, it only acts as a normal voice chat with no proximity, or server link.

**Comment by magneticflux-** [comment]
First follow the troubleshooting steps: https://github.com/magneticflux-/fabric-mumblelink-mod/wiki/Troubleshooting

What versions of mods are you using on the server and the client? What version of Mumble are you using?

**Comment by JackBMX637** [comment]
the issue is resolved, I had incorrectly booted mumble and Minecraft.
