### ISSUE TITLE
compatibility with mumble 1.4.x snapshots

### ISSUE THREAD

**Issue by greener-dot-ca** [magneticflux-/fabric-mumblelink-mod#73]
Is this mod expected to work with Mumble 1.4.x versions?

Seems the mod registers with the Mumble client (seems the plugin architecture on 1.4.x isn't as verbose as 1.3.x since it doesn't show it's specifically the Minecraft mod), but I don't think I'm ever put into positional audio.

Tried with 1.4.0 snapshot 6 on MacOS x86 and a self compiled version of 1.4.x branch on MacOS arm (with Minecraft running on a native arm JDK).

**Comment by magneticflux-** [comment]
I expect this mod to continue working with Mumble 1.4.x. Inspecting the Mumble source code (https://github.com/mumble-voip/mumble/blame/1.4.x/plugins/link/link-posix.cpp#L139) I don't see any changes that would affect compatibility.

I don't have access to macOS hardware, so the testing I've done is very light and is actually based on BSD Unix headers. If you're willing, I'd appreciate having a "guinea pig" to test macOS code on!

**Comment by greener-dot-ca** [comment]
Yup, I can definitely help with testing on M1 Mac.

**Comment by greener-dot-ca** [comment]
I know they've revamped the plug-in architecture and the original link plugin actually inherits a legacy header to make it work..  I wonder if something in the new framework is messing with it now.

**Comment by magneticflux-** [comment]
The first thing I'd like to make sure works is the loading of native code (located here https://github.com/magneticflux-/jvm-shared-memory). There's a suite of tests that you can run using `./gradlew test`.

I can be reached on Discord as `magneticflux-#8806`. I'm most active in the Fabric and Jellysquid servers.

I'll update this issue when we have more info about what's going wrong and how to fix it.

**Comment by magneticflux-** [comment]
Just noticed I forgot to post the followup last year, it didn't actually take a year to fix: https://github.com/magneticflux-/jvm-shared-memory/issues/11
