### ISSUE TITLE
Lunar client and fabric loader mumblelink arent compatible with each other.

### ISSUE THREAD

**Issue by Faisl100** [magneticflux-/fabric-mumblelink-mod#76]
I found out with my server that only lunar client's prox will work with other lunar clients and the rest will be heard from everywhere, and fabric loader users' prox will only work with other fabric users. I have tried different fabric mumblelink versions to fix this so fabric can proximity with lunar but couldn't get it to work. Is there a reason for this, or even a fix?

Lunar client 1.17.1 has a built-in mumblelink mod, and yes, I have followed the troubleshooting steps with all players, all good.

**Comment by magneticflux-** [comment]
This is Lunar client's problem; open an issue with them. The developer of the original Forge mod and I agreed to a standard format for cross-compatibility that other clients should adopt: https://github.com/zsawyer/MumbleLink/issues/38 and https://github.com/zsawyer/MumbleLink/pull/41
