### ISSUE TITLE
Request - Mod for 1.18

### ISSUE THREAD

**Issue by Wensted** [magneticflux-/fabric-mumblelink-mod#81]
I was wondering if there was a mod for 1.18 or if there is one being made

**Comment by magneticflux-** [comment]
I'd like to resolve https://github.com/zsawyer/MumbleLink/issues/55 before publishing a 1.18 build so there aren't mid-version incompatibilities.

**Comment by magneticflux-** [comment]
@Wensted If you _need_ a version for 1.18 and are willing to update to avoid incompatibilities when an official release is out, you can open up the jar and edit `fabric.mod.json` to require Minecraft `1.18.x` instead of `1.17.x` and it should probably work just fine.

**Comment by Wensted** [comment]
alright, thanks

**Comment by Talalchan** [comment]
game crashes when you edit fabric.mod.json to require minecraft 1.19 instead of 1.17
