### ISSUE TITLE
You'll need a new app to open this mumble link

### ISSUE THREAD

**Issue by chitinlink** [magneticflux-/fabric-mumblelink-mod#82]
mumble:// URLs seem to not be registered on my mumble installation, and I can't figure out how to fix that. I have a fresh install of Mumble 1.4.230.

![image](https://user-images.githubusercontent.com/52284719/150896239-2af91174-b73a-4072-88d2-6407384374fd.png)

Any ideas?

**Comment by magneticflux-** [comment]
Looks like this issue: https://github.com/mumble-voip/mumble/issues/5473
We can't fix it on our end, so we're just waiting on Mumble. If nothing gets done in a few days I'll take a stab at a PR to Mumble.

**Comment by magneticflux-** [comment]
@chitinlink If you want to test a dev build of Mumble `1.5.x`, you can download a build from my PR that fixes the installer here: https://dev.azure.com/Mumble-VoIP/c819eb06-7b22-4ef3-bbcd-860094454eb3/_apis/build/builds/5743/artifacts?artifactName=Windows%20%28x64%29%20installer&api-version=7.0&%24format=zip (~100MB download)

Just remember to reinstall when the fix has been backported to `1.4.x` so you still get other bugfixes!

**Comment by chitinlink** [comment]
@magneticflux- Sorry for the late reply, but I tested this build and it works, yeah. Thank you very much.
